name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Angular App to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        run: |
          # Create .ssh directory if it doesn't exist
          mkdir -p ~/.ssh
          
          # Save the private key to a file
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          
          # Set the correct permissions for the private key
          chmod 600 ~/.ssh/id_rsa
          
          # Log the permissions of the .ssh directory and private key
          echo "Logging permissions of ~/.ssh directory:"
          ls -ld ~/.ssh
          ls -l ~/.ssh/id_rsa

          # Log the fingerprint of the private key to ensure it's the right key
          ssh-keygen -lf ~/.ssh/id_rsa || true

      - name: Deploy to EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/home/ec2-user"
          RSYNC_OPTIONS: "-avz -e 'ssh -o StrictHostKeyChecking=no' -vv"

      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo yum -y update
            sudo yum install -y httpd
            sudo yum install -y nodejs npm
            
            cd /home/ec2-user/angular-app
            
            npm ci
            
            npm run build --prod
            
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html
            
            sudo systemctl start httpd
            sudo systemctl enable httpd
            
            sudo systemctl restart httpd
