name: Deploy Angular App to EC2

on:
  push:
    branches:
      - main  # or whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # specify your Node.js version

      # Install dependencies with legacy peer dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Build the Angular app
      - name: Build Angular App
        run: |
          npm run build --prod

      # Set up SSH key
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Add EC2 host to known hosts to prevent SSH prompt
      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts || echo "Failed to add EC2 host to known hosts"
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}  # EC2 public IP or DNS from GitHub secrets

      # Debugging step: Show EC2_HOST value
      - name: Debug EC2_HOST value
        run: echo "EC2_HOST: $EC2_HOST"

      # Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@$EC2_HOST << 'EOF'
            cd /path/to/your/angular/app
            git pull origin main  # Ensure your app is up-to-date
            rm -rf dist  # Remove old build files
            cp -r /path/to/your/angular/app/dist/* /var/www/html/  # Copy the new build to Nginx's root directory
            sudo systemctl restart nginx  # Restart Nginx to serve the new app
          EOF
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Your private SSH key stored in GitHub Secrets
          EC2_HOST: ${{ secrets.EC2_HOST }}  # Your EC2 instance public IP or DNS stored in GitHub Secrets
